overlay = "."
uploaders = ["Mikhail Kazantsev <kazan417@gmail.com>"]
summary = "Utility for identifying duplicate photos"
description = "Identifies duplicate photos regardless of scale or file format. Photodedupe is a command line utility for identifying duplicate photos regardless of whether the images have been scaled or have differing file formats. It compares the image content visually and does not rely on metadata or file hashes to perform the de-duplication."
section = "utils"
[source]
section = "utils"
build_depends_excludes = [
  "librust-image-0.25+default-dev (<< 0.25.6-~~)"
]
[packages.lib]
test_is_broken = true
depends = ["pandoc (>= 3.1)"]
[packages.bin]
section="utils"
summary = "Utility for identifying duplicate photos"
description = "Identifies duplicate photos regardless of scale or file format. Photodedupe is a command line utility for identifying duplicate photos regardless of whether the images have been scaled or have differing file formats. It compares the image content visually and does not rely on metadata or file hashes to perform the de-duplication."
